### PR TITLE
Add plugin compatibility UUID for 10.12

### PR DESCRIPTION
**Pull request by jgavris**
Working for me on 10.12.2

### CODE REVIEW

**Comment by kesselborn** [comment]
:+1: ... can confirm that the plugin works with this pull request (without it does not on Sierra 10.12.2)

**Comment by chadyj** [comment]
Works for me on 10.12.2 👍

**Comment by Grolubao** [comment]
I can't seem to find this branch, how can I get these changes?

**Comment by jgavris** [comment]
@Grolubao You can clone my fork of it and check out this branch https://github.com/jgavris/GMailinator/tree/sierra-uuid

**Comment by Grolubao** [comment]
Cheers mate! Works perfectly! Finally, gmail shortcuts in my Mail

**Pull request closed without merging**
